### ISSUE TITLE
 Sorry!  We could not found your streamer site! - How fix it ? and database password problem ?

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube-Encoder#64] opened 2018-05-04 17:25 UTC
Hello there, i m just frech install YouPHPTube-Encoder : 

i have this error : 

Sorry!
We could not found your streamer site!

![image](https://user-images.githubusercontent.com/32466950/39642052-9b72fbe6-4fd0-11e8-9db9-73589ff29f46.png)

my website is : 
![image](https://user-images.githubusercontent.com/32466950/39642062-a4198260-4fd0-11e8-8339-2d1ac3b0ed21.png)

and on log i have : 

```
root@ubuntu:/var/www/html/YouPHPTube-Encoder/videos# tail -f youphptube.log
[04-May-2018 19:20:29 Europe/Berlin] https://192.168.50.42/YouPHPTube/ == https://192.168.50.42/YouPHPTube/
[04-May-2018 19:20:44 Europe/Berlin] https://192.168.50.42/YouPHPTube/ == https://192.168.50.42/YouPHPTube/
[04-May-2018 19:21:26 Europe/Berlin] https://192.168.50.42/YouPHPTube/ == https://192.168.50.42/YouPHPTube/
[04-May-2018 19:21:31 Europe/Berlin] https://192.168.50.42/YouPHPTube/ == https://192.168.50.42/YouPHPTube/
```

can u please explain me this error : 

and something i can't understand on the database u can see the password with no encrytion : 

![image](https://user-images.githubusercontent.com/32466950/39642108-cf987482-4fd0-11e8-987c-e464e18b9f67.png)

WHat ??

**Comment by DanielnetoDotCom** [comment] 2018-05-04 20:31
I am not sure, but looks like you have an invalid ssl certificate

**Comment by gamersalpha** [comment] 2018-05-04 21:58
Hello, 
yes i have an invalid certificat ?

someone found a solution for the stream site here : 
https://github.com/DanielnetoDotCom/YouPHPTube/issues/637

i think same probléme on the encoder site

**Comment by gamersalpha** [comment] 2018-05-08 08:15
Hello, 

do u think u will be fix this problem ?

to make youhphtube-Encoder web site working on invalide ssl certificate

thanks

**Comment by hersche** [comment] 2018-05-10 04:48
problem should be fixed with upper PR #66 already.

if you can confirm it works, can you also close the issue?

please hold in mind that allow_url_fopen needs to be enabled for this and for the moment.

**Closed** 2018-05-10 12:39 UTC

**Comment by darkjedeye** [comment] 2020-03-17 13:40
Hi guys.... just installed today, and i am having this issue with the encoder aswell... running on a internal network with outside veiwing access on my side... and Sorry!
We could not find your streamer site!

**Comment by DanielnetoDotCom** [comment] 2020-03-18 12:42
Your site URL may not match with the defined allowedStreamersURL in your Encoder

Try to run this in your MySQL

    UPDATE `[avideo-encoder]`.`configurations` SET `allowedStreamersURL`='' WHERE `id`='1';

this will make your encoder public

**Comment by darkjedeye** [comment] 2020-03-18 13:07
Thanks

Regards,
Eric
0714671302

**Comment by darkjedeye** [comment] 2020-03-18 13:59
i am trying your fix on the one machine i installe on, but on the other i keep getting {"files":[{"error":"File is too big","type":"video/mp4","name":"1. Git Init.mp4","size":9351686}]}

**Comment by DanielnetoDotCom** [comment] 2020-03-19 12:35
Try to increase the file size limit in your php.ini

**Comment by MaryLu78** [comment] 2021-02-25 16:00
Hi Guys, I installed YouPhpTube as per this guide: https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server#comment-149314

But when I'm trying to Sign-in from /upload directory where Avideo-Encoder is installed, I have the same message above; "We could not find your streamer site!".

I don't use SSL / HTTPS, I deployed everything without HTTPS, so site should work with HTTP.

Where is the issue?

**Comment by DanielnetoDotCom** [comment] 2021-02-26 13:10
> Hi Guys, I installed YouPhpTube as per this guide: https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server#comment-149314

I do not know this guide

this is old but it may help you
https://tutorials.avideo.com/video/27/how-to-install-youphptube-in-a-fresh-ubuntu-server

**Comment by cw1245** [comment] 2021-04-12 16:55
> Your site URL may not match with the defined allowedStreamersURL in your Encoder
> 
> Try to run this in your MySQL
> 
> ```
> UPDATE `[avideo-encoder]`.`configurations` SET `allowedStreamersURL`='' WHERE `id`='1';
> ```
> 
> this will make your encoder public

hi it didn't work. can you please check? I'm having the same problem...

**Comment by DanielnetoDotCom** [comment] 2021-04-12 22:43
The thing is I am not having this problem, I cannot help on my side.

check your encoder logs for some clue

**Comment by MaryLu78** [comment] 2021-04-13 02:54
I resolved this issue last time by using a real URL (FQDN) not the IP address of the machine.

The issue is that you can't refer to the streamer as local as I remember, it has to be a recognized URL from your system. As i remember i configured my DNS to have the FQDN.

**Comment by cw1245** [comment] 2021-04-13 05:19
> I resolved this issue last time by using a real URL (FQDN) not the IP address of the machine.
> 
> The issue is that you can't refer to the streamer as local as I remember, it has to be a recognized URL from your system. As i remember i configured my DNS to have the FQDN.

I'm already using a real URL, but still having the same problem.
